const data = [
    {
        title: 'Never',
        album: '',
        artistes: ['Gyalkapone'],
        cover: '/images/never.jpg',
        liked: true,
        explicit: true,
        audio: '/audio/Never.mp3',
    },
    {
        title: 'Brik Pan Brik',
        album: '',
        artistes: ['Skillibeng'],
        cover: '/images/brikpanbrik.jpg',
        liked: true,
        explicit: false,
        audio: '/audio/BrikPonBrik.mp3',
    },
    {
        title: 'Tuscan Leather',
        album: 'Nothing Was The Same',
        artistes: ['Drake'],
        cover: '/images/ntws.jpg',
        liked: false,
        explicit: true,
        audio: '/audio/TuscanLeather.mp3',
    },
    {
        title: 'Bad Idea',
        album: 'The Lost Boy',
        artistes: ['YBN Cordae', 'Chance The Rapper'],
        cover: '/images/badidea.jpg',
        liked: true,
        explicit: true,
        audio: '/audio/BadIdea.mp3',
    },
    {
        title: 'LOVE AGAIN',
        album: 'CASE STUDY 01',
        artistes: ['Daniel Caesar', 'Brandy'],
        cover: '/images/casestudy.jpg',
        liked: true,
        explicit: false,
        audio: '/audio/LoveAgain.mp3',
    },

    {
        title: 'P*$$Y Fairy (OTW)',
        album: '',
        artistes: ['Jhene Aiko'],
        cover: '/images/chillombo.jpg',
        liked: false,
        explicit: true,
        audio: '/audio/Fairy.mp3',
    },
    {
        title: 'I Spy',
        album: '',
        artistes: ['Lila Ike'],
        cover: '/images/ispy.png',
        liked: true,
        explicit: false,
        audio: '/audio/ISpy.mp3',
    },
]

export default data
